# These limits are used by MoveIt and augment/override the definitions in ur_description.
#
# While the robot does not inherently have any limits on joint accelerations (only on torques),
# MoveIt needs them for time parametrization. They were chosen conservatively to work in most
# cases. For specific applications, higher values might lead to better execution performance.
#
# Position, velocity, and effort limits are defined in the URDF and will be loaded from there.
# Only acceleration limits are specified here as they are needed by MoveIt's time parameterization.

joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    max_acceleration: 2.5
  shoulder_lift_joint:
    has_acceleration_limits: true
    max_acceleration: 2.5
  elbow_joint:
    has_acceleration_limits: true
    max_acceleration: 2.5
  wrist_1_joint:
    has_acceleration_limits: true
    max_acceleration: 2.5
  wrist_2_joint:
    has_acceleration_limits: true
    max_acceleration: 2.5
  wrist_3_joint:
    has_acceleration_limits: true
    max_acceleration: 2.5