kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.18075500364162198
    roll: -0
    pitch: 0
    yaw: -1.180880194392997e-07
  upper_arm:
    x: 5.4095027875262194e-05
    y: 0
    z: 0
    roll: 1.5710412989478866
    pitch: 0
    yaw: -1.5547617220335042e-06
  forearm:
    x: -0.61213404542263605
    y: 0
    z: 0
    roll: 0.00045193287828353574
    pitch: 0.00017391605431474723
    yaw: 9.1557452330862967e-07
  wrist_1:
    x: -0.57124642012963645
    y: 0.0014958818338927601
    z: 0.1741733900753753
    roll: 3.1330044010715796
    pitch: -3.1414326217832058
    yaw: -3.1415899988516385
  wrist_2:
    x: 5.7359022271425831e-05
    y: -0.11972609030275563
    z: 0.00013336911645701836
    roll: 1.5696823752664171
    pitch: 0
    yaw: -4.4360081172603594e-07
  wrist_3:
    x: 5.7403669991257026e-05
    y: 0.1155365523480802
    z: 9.1816307941108448e-05
    roll: 1.5715910215191768
    pitch: 3.1415926535897931
    yaw: 3.1415921065958909
  hash: calib_2612675289436167309